# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'  # Of 'AzureStorage' als je zelf een distributie uploadt

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

- script: |
    echo "Setting JAVA_HOME to Java 21"
    export JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
    mvn -version
    mvn clean install
  displayName: 'Build met Java 21'
