# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJava@1
    inputs:
      versionSpec: '21'
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

      
- script: |
    echo "Java version:"
    java -version
    echo "Available versions:"
    sudo update-alternatives --display java
  displayName: 'Check Java version'
